export default {
  events: {
    name: "Events Director",
    open: "2",
    description: "The Events Director is responsible for the day to day logistics of TMG events and year-long timeline. Working closely with the Vice-President of Operations, this position will be facilitating both internal workshops and the external case competition to ensure that all stakeholders are satisfied with relevant projects.",
    qualification: ["Develop a year-long plan of events for the 2020/2021 TMG team",
    "Responsible for the logistics of both internal and external events",
    "Plan the structure of TMG’s annual case competition",
    "Plan the structures of TMG’s regular internal workshops",
    "Collaborate with the Management Co-Op office to facilitate internal events.",],
    skill: ["Creativity and the ability to consistently think outside the box",
    "Exceptional time management skills to ensure deadlines are met",
    "Strong ability to thrive under pressure and multitask",
    "Prior experience in Excel is an asset.",],
    extra: ""
  },
  project: {
    name: "Project Manager",
    open: "1",
    description: "The Project Manager is responsible for all internal communications within TMG. This position will work very closely with the TMG senior team to ensure all team goals are being met and that all meetings are conducted efficiently and productively. While this position can be considered the \"productivity manager\" of the club, the Project Manager will also be given ample opportunity to organize internal events to encourage teamwork, boost club morale and work with various departments whenever necessary.",
    qualification: ["Create and manage project-management tool to ensure all strategic deadlines and objectives are being met ",
    "Organize team meetings and provide insight and hands-on support wherever necessary",
    "Plan and lead internal-facing retreats, events and skill-building initiatives throughout the year",
    "Work with Directors to manage workload and overcome any obstacles in the way of achieving club goals",
    "Assist Operations team during the lead-up to TMG's flagship events to ensure sufficient support is provided",],
    skill: ["High level of initiative and ability to work independently",
    "Ability to manage a variety of tight, overlapping deadlines",
    "Event planning or prior experience in the field is an asset",
    "Strong interpersonal and communications skills",
    "Supreme time management and organization skills",],
    extra: ""
  },
  marketing: {
    name: "Marketing Director",
    open: "2",
    description: "The Marketing Director is responsible for the branding of TMG, as well as all campaigns to be executed throughout the year. Working closely with the Vice-President of Communications, this position will be leading the charge when it comes to developing marketing materials (either developed in-house or outsourced for internal and/or external purposes), creating a fundamental plan for promotions throughout the year and digital advertisements that attract students, alumni and corporate partners.",
    qualification: ["Create a year-long marketing plan that incorporates various campaigns and brand activations",
      "Work with the Vice President of Communications to maintain a unique online brand throughout all promotions",
      "Work with the Social Media Director to ensure that the club has a consistent and regular level of communication",
      "Develop simple, effective marketing materials and snackable content for internal and external purposes",
      "Launch strategic partnership campaigns that raise awareness about sponsors and the overall delegate experience"],
    skill: [
      "Creativity and the ability to consistently think outside the box",
      "Thorough understanding of TMG's target audience",
      "Exceptional time management skills to ensure deadlines are met",
      "Strong ability to thrive under pressure and multitask",
      "Prior experience in design or video-editing programs is an asset*"
    ],
    extra: "* Please provide a portfolio of creative work."
  },
  social: {
    name: "Social Media Director",
    open: "1",
    description: "The Social Media Director is responsible for TMG's external-facing communication. All social medias (Facebook, Instagram, LinkedIn, TikTok, etc.) will be operated completely by this Director. Working very closely with the Vice President of Communications and Marketing Directors, the Social Media Director will ensure that TMG has a strong, consistent, highly-engaging brand year-round. A proper understanding of the target audience will be required to thrive in this role.",
    qualification: ["Launch campaigns and promotions created by the Communications team on all owned channels",
    "Evaluate social media metrics regularly and provide quantitative recommendations to grow follower base",
    "Ensure audience engagement is high throughout the year and that launches are scheduled well in advance",
    "Add on to the TMG brand by creating simple, effective collateral in conjunction with existing creative material",
    "Seek opportunities to collaborate with other brands, events and initiatives to further improve brand awareness",],
    skill: ["Strong scheduling and organization skills",
    "Thorough understanding of TMG's target audience",
    "Creativity and the ability to consistently think outside the box",
    "Analytical skills with the ability to communicate new ideas",
    "Prior experience in a social media and/or creative design role not required, but is an asset",],
    extra: ""
  },
  corporate: {
    name: "Corporate Relations Director",
    open: "3",
    description: "The Corporate Relations Director is responsible for the procurement of funds for TMG and managing sponsor relationships throughout the year. They will work directly with the Vice President of Business Development and co-presidents to ensure that sponsorships are strategic and mutually beneficial to the long-term growth of both parties.",
    qualification: ["Liaison between the department of Management and TMG to continually foster relationship",
    "Leverage corporate sponsorships with the Vice President of Business Development to fund the club’s operations throughout the year",
    "Maintain relations with external stakeholders and TMG alumni",
    "Develop a strategic partnership with different companies that set sponsorships up for long term growth",],
    skill: ["Ability to present and think on your feet",
    "Thorough understanding of TMG's brand and assets",
    "Exceptional time management skills to ensure deadlines are met",
    "Strong ability to thrive under pressure and multitask",],
    extra: ""
  },
  finance: {
    name: "Finance Director",
    open: "1",
    description: "The Finance Director is responsible for the financial security and stability of the club. This Director will work closely with the senior team, as well as Corporate Relations Directors, to ensure TMG's financial well-being. Budgeting and forecasts will be developed by this Director to allow various team members to perform their duties (i.e. Events Directors). Making sure that the club's financial information is secure, but also easily communicable to all necessary stakeholders is another important requirement for this position.",
    qualification: ["Create budgets and forecasts using existing funds and predicted inflows to made decisions",
    "Work with various team members to ensure financial requirements are met for them to perform their duties",
    "Administer and ensure the security of all financial information throughout the year",
    "Seek opportunities for process efficiencies in coordination with various university and financial organizations",
    "Heavy involvement in the Business Development team's planning and funding efforts",],
    skill: ["Strong quantitative skills with the ability to communicate insights",
    "Excel proficiency is an asset",
    "Exceptional teamwork and collaborative skills",
    "Highly organized and efficient",
    "Money management and budgeting abilities",],
    extra: ""
  },
  curriculum: {
    name: "Curriculum Director",
    open: "2",
    description: "The Curriculum Director is responsible for the workshop content for TMG as well as the marketing cases. Working closely with the Vice-President of Curriculum and Academic Advisor, this position will be leading the charge when it comes to developing the curriculum of our in-house case competition.",
    qualification: ["Create a year-long curriculum plan to write cases for the TMG case competition",
    "Work with the Operations team to plan instructive workshops for the UTSC Management Community in marketing",
    "Collaborate with the Academic Advisor to develop relevant and challenging business cases",
    "Launch strategic partnership campaigns that raise awareness about sponsors and the overall delegate experience",],
    skill: ["Creativity and the ability to consistently think outside the box",
    "Thorough understanding of marketing concepts",
    "Exceptional time management skills to ensure deadlines are met",
    "Strong ability to thrive under pressure and multitask",],
    extra: "* Please provide a writing sample with your application."
  },
}