export default {
  SET_INFO: "SET_INFO",
  UPDATE_INFO: "UPDATE_INFO",
  SET_LOGIN_LOADING: "SET_LOGIN_LOADING",
  UNSET_LOGIN_LOADING: "UNSET_LOGIN_LOADING",
  SET_AUTHENTICATED: "SET_AUTHENTICATED",
}