export default {
  SET_INFO: "SET_INFO",
  UPDATE_INFO: "UPDATE_INFO",
  SET_LOGIN_LOADING: "SET_LOGIN_LOADING",
  UNSET_LOGIN_LOADING: "UNSET_LOGIN_LOADING",
  SET_AUTHENTICATED: "SET_AUTHENTICATED",
  ADD_NEW_SLIDE: "ADD_NEW_SLIDE",
  SET_CAROUSEL_LOADING: "SET_CAROUSEL_LOADING",
  SET_CAROUSEL: "SET_CAROUSEL",
  API_UNAUTHORIZED: "API_UNAUTHORIZED",
}